[package]
name = "tosho"
version = "0.1.0"
authors = ["Tristan King <tristan.king@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
quick-xml = "0.17"
postgres = { version = "0.15", features = ["with-chrono"] }
dotenv = "0.15"
chrono = "0.4"
clap = "2.33"
#reqwest = "0.9"
curl = "0.4"
regex = "1.1"
lazy_static = "1.3"
url = "2.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rusqlite = "0.21"